export const rowsEngg = [
  {
    SNo: 1,
    CollegeCode: "Q7",
    CollegeName: "Avanthi Institute of Engineering and Technology, Bhogapuram",
    District: "Vizianagaram",
    CollegeType: "Engineering",
    wURL: "http://aietta.ac.in/",
    Address: "Cherukupally(Village), Near Tagarapuvalasa bridge, Bhogapuram(Mandal)Vizianagaram-531162",
    PrincipalName: "Dr. B. Murali Krishna",
    Phone: "79979 03696",
    Email: "pricipal@aietta.ac.in",
    AutonomousYear: "2024",
  },
  {
    SNo: 2,
    CollegeCode: "34",
    CollegeName: "GMR Institute of Technology, Rajam",
    District: "Vizianagaram",
    CollegeType: "Engineering",
    wURL: "http://www.gmrit.org/",
    Address: "GMR Nagar, Rajam - 532127, Vizianagarm, District",
    PrincipalName: "Dr. C.L.V.R.S.V. Prasad",
    Phone: "94414 06014",
    Email: "prasad.clvrsv@gmrgroup.in",
    AutonomousYear: "2012",
  },
  {
    SNo: 3,
    CollegeCode: "KD",
    CollegeName: "Lendi Institute of Engineering & Technology, Jonnada",
    District: "Vizianagaram",
    CollegeType: "Engineering",
    wURL: "https://www.lendi.org/",
    Address: "Jonnada(Vill), Denkada (Mandal), Vizianagaram-535005",
    PrincipalName: "Dr. V.V. Rama Reddy",
    Phone: "94903 04747",
    Email: "lendi_2008@yahoo.com",
    AutonomousYear: "2019",
  },
  {
    SNo: 4,
    CollegeCode: "33",
    CollegeName: "Maharaj Vijayaram Gajapathi Raj College of Engineering (MVGR), Chintalavalasa",
    District: "Vizianagaram",
    CollegeType: "Engineering",
    wURL: "https://www.mvgrce.com/",
    Address: "Vizianagaram Campus, Chintalavalasa,Vizianagaram - 535005",
    PrincipalName: "Dr. YMC.Sekhar",
    Phone: "9440018657",
    Email: "principal@mvgrce.edu.in",
    AutonomousYear: "2015",
  },
  {
    SNo: 5,
    CollegeCode: "98",
    CollegeName: "Raghu Engineering College, Dakamarri",
    District: "Visakhapatnam",
    CollegeType: "Engineering",
    wURL: "https://raghuenggcollege.com/",
    Address: "Dakamarri(V),Bheemunipatnam- (M), Visakpatnam District - 531162.",
    PrincipalName: "Dr. A.Vijay Kumar",
    Phone: "9963261138",
    Email: "principal@racollege.com",
    AutonomousYear: "2017",
  },
  {
    SNo: 6,
    CollegeCode: "L3",
    CollegeName: "Vignans Institute of Information Technology, Duvvada",
    District: "Visakhapatnam",
    CollegeType: "Engineering",
    wURL: "https://vignaniit.edu.in/",
    Address: "Beside VSEZ, Near Duvvada Railway Station, Kurmannaoalem, Visakhapatnam Dist-530049",
    PrincipalName: "Dr. J. Sudhakar",
    Phone: "90520 66699",
    Email: "sudhakar.jyo@gmail.com",
    AutonomousYear: "2017",
  },
  {
    SNo: 7,
    CollegeCode: "NU",
    CollegeName: "Nadimpalli Satyanarayana Raju Institute of Technology, Sontyam",
    District: "Visakhapatnam",
    CollegeType: "Engineering",
    wURL: "http://www.nsrit.edu.in/",
    Address: "Pendurthi Anandapuram Highway,Sontyam, Visakhapatnam-531173",
    PrincipalName: "Dr. S. Sambhu Prasad",
    Phone: "95330 33334",
    Email: "principal@nsrit.edu.in",
    AutonomousYear: "2020",
  },
  {
    SNo: 8,
    CollegeCode: "81",
    CollegeName: "Avanthi Institute of Engineering and Technology, Makavarapalem",
    District: "Anakapalli",
    CollegeType: "Engineering",
    wURL: "http://avanthienggcollege.ac.in/",
    Address: "Makavarapalem,Narsipatnam , Anakapalli Dist. - 531113",
    PrincipalName: "Dr. C.P.V.N.J. MohanRao",
    Phone: "98491 47304",
    Email: "Principal_aiet@yahoo.com",
    AutonomousYear: "2024",
  },
  {
    SNo: 9,
    CollegeCode: "U4",
    CollegeName: "Dadi Institute of Engineering & Technology, Anakapalli",
    District: "Anakapalli",
    CollegeType: "Engineering",
    wURL: "https://www.diet.edu.in/",
    Address: "NH-16, By pass Road , Anakapalle-531002",
    PrincipalName: "Dr. R. Vaikunta Rao",
    Phone: "99639 93229",
    Email: "Principal@diet.edu.in",
    AutonomousYear: "2023",
  },
  {
    SNo: 10,
    CollegeCode: "A5",
    CollegeName: "Aditya Institute of Technology and Management, Tekkali",
    District: "Srikakulam",
    CollegeType: "Engineering",
    wURL: "https://www.adityatekkali.edu.in/",
    Address: "Tekkali(Mandal), Srikakulam Dist - 532201",
    PrincipalName: "Dr. A.S. Srinivasa Rao",
    Phone: "94401 21465",
    Email: "principal@adityatekkali.edu.in",
    AutonomousYear: "2013",
  },
  {
    SNo: 11,
    CollegeCode: "6C",
    CollegeName: "Miracle Educational Society Group of Institutions, Bhogapuram",
    District: "Vizianagaram",
    CollegeType: "Engineering",
    wURL: "http://www.miracleeducationalsociety.com/",
    Address: "Miracle City, Bhogapuram - 535216, Vizianagaram Dist",
    PrincipalName: "Dr. A. Arjuna Rao",
    Phone: "94408 03924",
    Email: "principal@miracleeducationalsociety.com",
    AutonomousYear: "2024",
  },
  {
    SNo: 12,
    CollegeCode: "NM",
    CollegeName: "Vignans Institute of Engineering for Women, Kapujaggarajupeta",
    District: "Visakhapatnam",
    CollegeType: "Engineering",
    wURL: "http://view.edu.in/",
    Address: "Kapujaggarajupeta, VSEZ Post, Visakhapatnam - 530049",
    PrincipalName: "Dr. Arundhati",
    Phone: "94419 57596",
    Email: "viewprincipal@gmail.com",
    AutonomousYear: "2023",
  },

  {
    SNo: 13,
    CollegeCode: "NR",
    CollegeName: "Baba Institute of Technology and Sciences, Bakkannapalem",
    District: "Visakhapatnam",
    CollegeType: "Engineering",
    wURL: "http://www.bitsvizag.com/",
    Address: "PM Palem, Bakkanapalem(V), Madhurawada(Post)- 530048",
    PrincipalName: "Dr. M.Rajan Babu",
    Phone: "9492618186",
    Email: "principal@bitsvizag.com",
    AutonomousYear: "2024",
  },
  {
    SNo: 14,
    CollegeCode: "NT",
    CollegeName: "Visakha Institute of Engineering & Technology, Narava",
    District: "Visakhapatnam",
    CollegeType: "Engineering",
    wURL: "http://vietvsp.com/",
    Address: "88th Division, Narava ,Gopalapatnam, Visakhapatnam-530027",
    PrincipalName: "Dr. G.V. Pradeep Varma",
    Phone: "94402 62833",
    Email: "principal@vietvsp.com",
    AutonomousYear: "2024",
  },
  {
    SNo: 15,
    CollegeCode: "W6",
    CollegeName: "Sri Sivani College of Engineering, Chilakapalem",
    District: "Srikakulam",
    CollegeType: "Engineering",
    wURL: "http://srisivani.com/",
    Address: "Chilakapalem(V), Etcherla (M),Srikakulam-532410, Andhra Pradesh",
    PrincipalName: "Dr. Yenda Srinivasa Rao",
    Phone: "94925 46575",
    Email: "principal_w6@yahoo.co.in",
    AutonomousYear: "2025",
  },

]

export const rowsPharmacy = [
  {
    SNo: 1,
    CollegeCode: "T5",
    CollegeName: "Avanthi Institute of Pharmaceutical Sciences, Cherukupalli",
    District: "Vizianagaram",
    CollegeType: "Pharmacy",
    wURL: "http://avanthipharma.ac.in/",
    Address: "Cherukupalli, Bhogapuram(M) Vizianagaram Dist - 531162",
    PrincipalName: "Dr. K.Purna Nagasree",
    Phone: "9398020669",
    Email: "principalavanthit5@gmail.com",
    AutonomousYear: "2025",
  },

  {
    SNo: 2,
    CollegeCode: "AC",
    CollegeName: "Vignan Institute of Pharmaceutical Technology, Duvvada",
    District: "Visakhapatnam",
    CollegeType: "Pharmacy",
    wURL: "http://viptvizag.in/",
    Address: "BesideVSEZ, Kapujag-garajupeta, Duvvada, Visakhapatnam-530049",
    PrincipalName: "Dr. Y. Srinivasa Rao",
    Phone: "98663 99928",
    Email: "viptvizag@gmail.com",
    AutonomousYear: "2024",
  },
];