
export const rowsEngg = [
  {
    SNo: 1,
    CollegeCode: "B6",
    CollegeName: "Satya Institute of Technology and Management Vizianagaram",
    District: "Vizianagaram",
    CollegeType: "Engineering",
    wURL: "https://www.sitam.co.in/",
    Type: "Permanent",
    JnanaBhumiCode: "23942",
  },
  {
    SNo: 2,
    CollegeCode: "HQ",
    CollegeName: "Avanthi Research and Technological Academy Basavapalem Bhogapuram",
    District: "Vizianagaram",
    CollegeType: "Engineering",
    wURL: "https://arta.ac.in/",
    Type: "Temporary",
    JnanaBhumiCode: "10902",
  },
  {
    SNo: 3,
    CollegeCode: "99",
    CollegeName: "Avanthi St.Theressa Institute of Engineering and Tech Garividi",
    District: "Vizianagaram",
    CollegeType: "Engineering",
    wURL: "https://www.sttheressaengg.ac.in/",
    Type: "Temporary",
    JnanaBhumiCode: "19819",
  },
  {
    SNo: 4,
    CollegeCode: "8K",
    CollegeName: "Gokul Group of Institutions Piridi Bobbili, Vizianagaram",
    District: "Vizianagaram",
    CollegeType: "Engineering",
    wURL: "http://www.gokulcollege.com/",
    Type: "Temporary",
    JnanaBhumiCode: "27640",
  },
  {
    SNo: 5,
    CollegeCode: "L6",
    CollegeName: "Chaitanya Engineering College Kommadi Madhurawada Visakhapatnam",
    District: "Visakhapatnam",
    CollegeType: "Engineering",
    wURL: "http://cec.ac.in/",
    Type: "Temporary",
    JnanaBhumiCode: "11357",
  },
  {
    SNo: 6,
    CollegeCode: "6E",
    CollegeName: "Gonna Institute of Information Technology and Sciences Aganampudi",
    District: "Anakapalli",
    CollegeType: "Engineering",
    wURL: "http://www.giits.in/",
    Type: "Temporary",
    JnanaBhumiCode: "22775",
  },
  {
    SNo: 7,
    CollegeCode: "6F",
    CollegeName: "Sai Ganapathi Engineering College Gidijala Anandapuram, Visakhapatnam",
    District: "Visakhapatnam",
    CollegeType: "Engineering",
    wURL: "https://www.sgec.edu.in/",
    Type: "Temporary",
    JnanaBhumiCode: "22797",
  },
  {
    SNo: 8,
    CollegeCode: "6J",
    CollegeName: "Simhadri Educational Society Group of Institutions Engineering College",
    District: "Anakapalli",
    CollegeType: "Engineering",
    wURL: "https://simhadhriedu.org/",
    Type: "Temporary",
    JnanaBhumiCode: "22803",
  },
  {
    SNo: 9,
    CollegeCode: "MT",
    CollegeName: "Sri Venkateswara College of Engineering and Technology, Etcherla, Srikakulam",
    District: "Srikakulam",
    CollegeType: "Engineering",
    wURL: "https://svcet.net/new/",
    Type: "Temporary",
    JnanaBhumiCode: "20869",
  },
  {
    SNo: 10,
    CollegeCode: "PC",
    CollegeName: "N S Raju Institute of Engineering & Technology Dakamarri Bheemunipatnam",
    District: "Visakhapatnam",
    CollegeType: "Engineering",
    wURL: "https://www.nsriet.edu.in/",
    Type: "Temporary",
    JnanaBhumiCode: "21465",
  },
  {
    SNo: 11,
    CollegeCode: "V1",
    CollegeName: "Behara College of Engineering and Technology",
    District: "Visakhapatnam",
    CollegeType: "Engineering",
    wURL: "https://beharaengg.edu.in/",
    Type: "Temporary",
    JnanaBhumiCode: "35292",
  },
];

export const rowsPharmacy = [
  {
    SNo: 1,
    CollegeCode: "HH",
    CollegeName: "Gokul College of Pharmacy, Piridi, Bobbili, Vizianagaram",
    District: "Vizianagaram",
    CollegeType: "Pharmacy",
    wURL: "https://www.gokulcollege.com/sites/Pharmacy/home.html",
    Type: "Temporary",
    JnanaBhumiCode: "12473",
  },
  {
    SNo: 2,
    CollegeCode: "B7",
    CollegeName: "Emmanuel College of Pharmacy Singannanbanda, Bheemunipatnam, Visakhapatnam",
    District: "Visakhapatnam",
    CollegeType: "Pharmacy",
    wURL: "https://emmanuelcollegeofpharmacy.com/",
    Type: "Temporary",
    JnanaBhumiCode: "12157",
  },
  {
    SNo: 3,
    CollegeCode: "PK",
    CollegeName: "Viswanadha Institute of Pharmaceutical Sciences Sontyam Visakhapatnam",
    District: "Visakhapatnam",
    CollegeType: "Pharmacy",
    wURL: "https://vnips.in/Home.html",
    Type: "Temporary",
    JnanaBhumiCode: "23219",
  },
  {
    SNo: 4,
    CollegeCode: "DA",
    CollegeName: "Sri Sivani College of Pharmacy Chilakapalem, Srikakulam",
    District: "Srikakulam",
    CollegeType: "Pharmacy",
    wURL: "https://srisivanisscp.com/",
    Type: "Temporary",
    JnanaBhumiCode: "19212",
  },
];

export const rowsMba = [
  {
    SNo: 1,
    CollegeCode: "C4",
    CollegeName: "All Saints PG College Visakhapatnam",
    District: "Visakhapatnam",
    CollegeType: "Management",
    wURL: "https://allsaintspgcollege.com/",
    Type: "Temporary",
    JnanaBhumiCode: "10275",
  },
  {
    SNo: 2,
    CollegeCode: "8M",
    CollegeName: "Visakha Institute of Management Science Dakamarri Bheemunipatnam",
    District: "Visakhapatnam",
    CollegeType: "Management",
    wURL: "http://vimsvizag.com/",
    Type: "Temporary",
    JnanaBhumiCode: "23606",
  },
];
