// searchItems.js
export const searchItems = [
    { path: "/", label: "Home" },
    { path: "/about-us", label: "About Us" },
    { path: "/about-us/about-jntugv", label: "About JNTU-GV" },
    { path: "/about-us/vision", label: "Vision" },
    { path: "/about-us/mission", label: "Mission" },
    { path: "/administration", label: "Administration" },
    { path: "/administration/chancellor", label: "Chancellor" },
    { path: "/administration/vice-chancellor", label: "Vice Chancellor" },
    { path: "/administration/registrar", label: "Registrar" },
    { path: "/academics", label: "Academics" },
    { path: "/academics/programs-offered", label: "Programs Offered" },
    { path: "/academics/admissions", label: "Admissions" },
    { path: "/academics/constituent-colleges", label: "Constituent Colleges" },
    { path: "/academics/affiliated-colleges", label: "Affiliated Colleges" },
    { path: "/academics/bos-chairman", label: "BOS Chairman" },
    { path: "/academics/calendar", label: "Academic Calendar" },
    { path: "/academics/academic-syllabus", label: "Academic Syllabus" },
    { path: "/directorates", label: "Directorates" },
    { path: "/directorates/academic-planning", label: "Academic Planning" },
    { path: "/directorates/academic-audit", label: "Academic Audit" },
    { path: "/directorates/evaluation", label: "Evaluation" },
    { path: "/directorates/admissions", label: "Admissions" },
    { path: "/directorates/placements", label: "IIIT & Placements" },
    { path: "/directorates/research", label: "Research & Development" },
    { path: "/directorates/alumni-relations", label: "Alumni Relations" },
    { path: "/directorates/iqac", label: "Internal Quality Assurance Cell" },
    { path: "/examination", label: "Examinations" },
    { path: "/examination/director-evaluation", label: "Director of Evaluation" },
    { path: "/examination/controller", label: "Controller of Examinations" },
    { path: "/examination/controller-sdc", label: "Additional Controller of Examinations-SDC" },
    { path: "/examination/controller1", label: "Additional Controller of Examinations-1" },
    { path: "/examination/controller2", label: "Additional Controller of Examinations-2" },
    { path: "/examination/controller3", label: "Additional Controller of Examinations-3" },
    { path: "/examination/controller-pg", label: "Additional Controller of Examinations-PG" },
    { path: "https://ums.campx.in/jntugv/jntugv/results", label: "Examination Results" }, // External link
    { path: "/contact-us", label: "Contact Us" },
    // Add more links as needed
  ];
  